cleanup

diff --git a/v03_pipeline/bin/vep b/v03_pipeline/bin/vep
--- a/v03_pipeline/bin/vep
+++ b/v03_pipeline/bin/vep
@@ -1,9 +1,20 @@
 #!/bin/bash
 
+set -eux
 
-REFERENCE_GENOME="\$1"
-shift
+REFERENCE_GENOME=${1:-GRCh38}
+VEP_DOCKER_IMAGE="gcr.io/seqr-project/vep-docker-image"
+
+case $REFERENCE_GENOME in
+  GRCh38)
+    ;;
+  GRCh37)
+    ;;
+   *)
+    echo "Invalid reference genome $REFERENCE_GENOME, should be GRCh37 or GRCh38"
+    exit 1
+esac
 
 # NB: the vep_data volume reference isn't absolute... couldn't get it to work.
-docker run --platform ${PLATFORM} -i -v vep_data/$REFERENCE_GENOME:/opt/vep/.vep/:ro gcr.io/seqr-project/vep-docker-image:${REFERENCE_GENOME} \
+docker run --platform linux/amd64 -i -v ~/vep_data/$REFERENCE_GENOME:/opt/vep/.vep/:ro $VEP_DOCKER_IMAGE:$REFERENCE_GENOME \
   /opt/vep/src/ensembl-vep/vep $@
